### ISSUE TITLE
[IMPROVEMENT] Command's name will collide with Apace Benchmark

### ISSUE THREAD

**Issue by hron84** [tamasd/ab#1]
Could you please provide another name for the command line interface than ab? It will collide if anyone has [Apache Benchmark](https://httpd.apache.org/docs/2.4/programs/ab.html) installed because it provides command with exactly same name.

`abunny` or `ufo` would be good here :smile:

**Comment by tamasd** [comment]
What do you think about `abt`?

**Comment by hron84** [comment]
Sounds cool.
